### ISSUE TITLE
Show ec2 instance name

### ISSUE THREAD

**Issue by Lusitaniae** [monitoringartist/grafana-aws-cloudwatch-dashboards#19]
On RDS dashboard we can choose by Instance name.
On EC2 I'm only able to pick by instance_id.

Should I replace it with instance name picker or instead make a new box to show the name?

PS: Same applies to EBS dashboard

**Comment by jangaraj** [comment]
EC2/EBS doesn't have field Instance name. It has only tag Name. There is already issue for general tag filtering, but it will need to create an additional dashboard(s) because it won't be backwards compatible. Also, some recent Grafana feature is required. Please comment https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards/issues/14 with your ideas. Thanks.
