### ISSUE TITLE
None of these work with the "hosted" or cloud based Grafana

### ISSUE THREAD

**Issue by david-crowdstreet** [monitoringartist/grafana-aws-cloudwatch-dashboards#22]
They seem to not properly use the Datasource even though it is tested working with manually created dashboards and dashboards imported from other sources.
Example with the "AWS EC2" Dashboard. Once imported a pop-up error messages says:
`
Templating init failed
Unable to call AWS API
`

I have attached a screen that of the error that appears on every graph. 
![screen shot 2017-10-02 at 10 33 28 am](https://user-images.githubusercontent.com/31673300/31090665-4b98ac9a-a75d-11e7-98e0-1ad30f9a511e.png)

**Comment by jangaraj** [comment]
Did you select correct dashboard variable values? For example `Region`?

**Comment by david-crowdstreet** [comment]
Thanks for the quick reply. I was able to get the EC2 version working. It
did require me to set every dashboard variable including instance and EBS
ID. I had the wrong impression that these would be auto created.

I have also not been able to get the AWS Billing dashboard to return any
information. I do not see the same variable requirements there. Is there
something additional required to get that dashboard working?

**Comment by jangaraj** [comment]
Unfortunately, that's how Grafana works.

No, you don't need an additional setting for AWS Billing. Check Grafana logs/browser console for more details.

I'm closing this issue because I don't see any problem with the dashboard here. Very likely it's an issue with your Grafana config/AWS IAM permissions. Unfortunately, these types of problems are not in the scope of this project.
